/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import io.vertx.core.Vertx;
import io.vertx.core.VertxOptions;
import io.vertx.core.file.FileSystemOptions;

public class MainVerticle {
    

    public static void main(String[] args) {
    	VertxOptions options = new VertxOptions().setFileSystemOptions(new FileSystemOptions().setFileCachingEnabled(true));
    	Vertx vertx = Vertx.vertx(options);
    	vertx.deployVerticle("verticles.HttpServerVerticle");
    	//vertx.deployVerticle("verticles.WebSocketVerticle");
    }
}
